name: Daily Commit Workflow

on:
  schedule:
    - cron: '50 2 * * *'  

permissions:
  contents: write

jobs:
  commit_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Add timestamped commit for 21f3001973@ds.study.iitm.ac.in
        run: |
          date +%s > daily_commit.txt

      - name: 21f3001973@ds.study.iitm.ac.in
        run: |
          git config --global user.name "21f3001973@ds.study.iitm.ac.in"
          git config --global user.email "21f3001973@ds.study.iitm.ac.in"

      - name: Commit and push changes
        run: |
          git add daily_commit.txt
          git commit -m "Daily automated commit by 21f3001973@ds.study.iitm.ac.in" || echo "No changes to commit"
          git pull --rebase origin main
          git push
