name: Daily Commit Workflow

on:
  schedule:
    - cron: '25 0 * * *'
    - cron: '25 1 * * *'
    - cron: '25 2 * * *'
    - cron: '25 3 * * *'
    - cron: '25 4 * * *'
    - cron: '25 5 * * *'
    - cron: '25 6 * * *'
    - cron: '25 7 * * *'
    - cron: '25 8 * * *'
    - cron: '25 9 * * *'
    - cron: '25 11 * * *'
    - cron: '25 12 * * *'
    - cron: '25 13 * * *'
    - cron: '25 14 * * *'
    - cron: '25 15 * * *'
    - cron: '25 16 * * *'
    - cron: '25 17 * * *'
    - cron: '25 18 * * *'
    - cron: '25 19 * * *'
    - cron: '25 20 * * *'
    - cron: '25 21 * * *'
    - cron: '25 22 * * *'
    - cron: '25 23 * * *'    

permissions:
  contents: write

jobs:
  commit_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Add timestamped commit for 21f3001973@ds.study.iitm.ac.in
        run: |
          date +%s > daily_commit.txt

      - name: Configure Git with 21f3001973@ds.study.iitm.ac.in
        run: |
          git config --global user.name "21f3001973@ds.study.iitm.ac.in"
          git config --global user.email "21f3001973@ds.study.iitm.ac.in"

      - name: Commit and push changes
        run: |
          git add daily_commit.txt
          git commit -m "Daily automated commit by 21f3001973@ds.study.iitm.ac.in" || echo "No changes to commit"
          git pull --rebase origin main
          git push
